package de.flexusma.ltmp.client.utils;

import com.esotericsoftware.kryo.Kryo;
import com.lilithsthrone.controller.xmlParsing.XMLUtil;
import com.lilithsthrone.game.Game;
import com.lilithsthrone.game.character.attributes.Attribute;
import com.lilithsthrone.game.character.body.CoverableArea;
import com.lilithsthrone.game.character.body.types.*;
import com.lilithsthrone.game.character.effects.StatusEffect;
import com.lilithsthrone.game.character.fetishes.Fetish;
import com.lilithsthrone.game.character.gender.Gender;
import com.lilithsthrone.game.character.npc.NPC;
import com.lilithsthrone.game.character.npc.dominion.DominionClubNPC;
import com.lilithsthrone.game.character.npc.dominion.Lilaya;
import com.lilithsthrone.game.character.npc.dominion.Scarlett;
import com.lilithsthrone.game.character.npc.misc.NPCOffspring;
import com.lilithsthrone.game.character.npc.submission.DarkSiren;
import com.lilithsthrone.game.character.npc.submission.Elizabeth;
import com.lilithsthrone.game.character.npc.submission.Lyssieth;
import com.lilithsthrone.game.character.persona.NameTriplet;
import com.lilithsthrone.game.character.persona.Occupation;
import com.lilithsthrone.game.character.persona.Relationship;
import com.lilithsthrone.game.character.persona.SexualOrientation;
import com.lilithsthrone.game.character.quests.Quest;
import com.lilithsthrone.game.character.quests.QuestLine;
import com.lilithsthrone.game.character.quests.QuestType;
import com.lilithsthrone.game.character.race.AbstractSubspecies;
import com.lilithsthrone.game.character.race.Race;
import com.lilithsthrone.game.character.race.RaceStage;
import com.lilithsthrone.game.character.race.Subspecies;
import com.lilithsthrone.game.dialogue.DialogueFlagValue;
import com.lilithsthrone.game.dialogue.eventLog.EventLogEntry;
import com.lilithsthrone.game.dialogue.utils.UtilText;
import com.lilithsthrone.game.inventory.CharacterInventory;
import com.lilithsthrone.game.inventory.ItemTag;
import com.lilithsthrone.game.inventory.Rarity;
import com.lilithsthrone.game.inventory.ShopTransaction;
import com.lilithsthrone.game.inventory.clothing.AbstractClothingType;
import com.lilithsthrone.game.inventory.clothing.ClothingType;
import com.lilithsthrone.game.inventory.item.AbstractItem;
import com.lilithsthrone.game.inventory.item.AbstractItemType;
import com.lilithsthrone.game.inventory.item.ItemType;
import com.lilithsthrone.game.inventory.weapon.AbstractWeaponType;
import com.lilithsthrone.game.inventory.weapon.WeaponType;
import com.lilithsthrone.game.sex.*;
import com.lilithsthrone.game.sex.managers.submission.SMLyssiethDemonTF;
import com.lilithsthrone.game.sex.positions.slots.SexSlotLyingDown;
import com.lilithsthrone.game.sex.sexActions.SexActionInterface;
import com.lilithsthrone.game.sex.sexActions.SexActionOrgasmOverride;
import com.lilithsthrone.game.sex.sexActions.SexActionType;
import com.lilithsthrone.game.sex.sexActions.baseActions.*;
import com.lilithsthrone.game.sex.sexActions.baseActionsMisc.*;
import com.lilithsthrone.game.sex.sexActions.baseActionsSelf.SelfFingerPenis;
import com.lilithsthrone.game.sex.sexActions.baseActionsSelfPartner.*;
import com.lilithsthrone.game.sex.sexActions.baseActionsSelfPlayer.*;
import com.lilithsthrone.game.sex.sexActions.universal.*;
import com.lilithsthrone.main.Main;
import com.lilithsthrone.utils.*;
import com.lilithsthrone.utils.colours.PresetColour;
import com.lilithsthrone.world.AbstractWorldType;
import com.lilithsthrone.world.WorldType;
import com.lilithsthrone.world.places.AbstractPlaceType;
import com.lilithsthrone.world.places.PlaceType;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

import java.time.LocalDateTime;
import java.util.*;

public class KryoRegDepend {

    public static void register(Kryo kryo){

        kryo.register(ClitAnus.class);
        kryo.register(ClitClit.class);
        kryo.register(ClitMouth.class);
        kryo.register(ClitVagina.class);
        kryo.register(FingerAnus.class);
        kryo.register(FingerBreasts.class);
        kryo.register(FingerBreastsCrotch.class);
        kryo.register(FingerClit.class);
        kryo.register(FingerMouth.class);
        kryo.register(FingerNipple.class);
        kryo.register(FingerNippleCrotch.class);
        kryo.register(FingerPenis.class);
        kryo.register(FingerVagina.class);
        kryo.register(FootMouth.class);
        kryo.register(PenisAnus.class);
        kryo.register(PenisAss.class);
        kryo.register(PenisBreasts.class);
        kryo.register(PenisBreastsCrotch.class);
        kryo.register(PenisFeet.class);
        kryo.register(PenisFoot.class);
        kryo.register(PenisMouth.class);
        kryo.register(PenisNipple.class);
        kryo.register(PenisNippleCrotch.class);
        kryo.register(PenisSpinneret.class);
        kryo.register(PenisThighs.class);
        kryo.register(PenisUrethraPenis.class);
        kryo.register(PenisUrethraVagina.class);
        kryo.register(PenisVagina.class);
        kryo.register(TailAnus.class);
        kryo.register(TailMouth.class);
        kryo.register(TailVagina.class);
        kryo.register(TentacleAnus.class);
        kryo.register(TentacleMouth.class);
        kryo.register(TentacleVagina.class);
        kryo.register(TongueAnus.class);
        kryo.register(TongueBreasts.class);
        kryo.register(TongueBreastsCrotch.class);
        kryo.register(TongueMound.class);
        kryo.register(TongueMouth.class);
        kryo.register(TongueNipple.class);
        kryo.register(TongueNippleCrotch.class);
        kryo.register(TongueVagina.class);
        kryo.register(ToyVagina.class);

        kryo.register(GenericActions.class);
        kryo.register(GenericOrgasms.class);
        kryo.register(GenericPositioning.class);
        kryo.register(GenericTalk.class);
        kryo.register(PartnerTalk.class);
        kryo.register(PlayerTalk.class);
        kryo.register(PositioningMenu.class);
        kryo.register(SadisticActions.class);
        kryo.register(SelfFingerPenis.class);

        kryo.register(PartnerSelfFingerAnus.class);
        kryo.register(PartnerSelfFingerBreasts.class);
        kryo.register(PartnerSelfFingerMouth.class);
        kryo.register(PartnerSelfFingerNipple.class);
        kryo.register(PartnerSelfFingerVagina.class);
        kryo.register(PartnerSelfNoPen.class);
        kryo.register(PartnerSelfPenisAnus.class);
        kryo.register(PartnerSelfPenisMouth.class);
        kryo.register(PartnerSelfPenisNipple.class);
        kryo.register(PartnerSelfPenisVagina.class);
        kryo.register(PartnerSelfTailAnus.class);
        kryo.register(PartnerSelfTailMouth.class);
        kryo.register(PartnerSelfTailNipple.class);
        kryo.register(PartnerSelfTailVagina.class);
        kryo.register(PartnerSelfTongueAnus.class);
        kryo.register(PartnerSelfTongueMouth.class);
        kryo.register(PartnerSelfTongueNipple.class);
        kryo.register(PartnerSelfTongueVagina.class);

        kryo.register(PlayerSelfFingerAnus.class);
        kryo.register(PlayerSelfFingerBreasts.class);
        kryo.register(PlayerSelfFingerCrotchNipple.class);
        kryo.register(PlayerSelfFingerMouth.class);
        kryo.register(PlayerSelfFingerNipple.class);
        kryo.register(PlayerSelfFingerVagina.class);
        kryo.register(PlayerSelfNoPen.class);
        kryo.register(PlayerSelfPenisAnus.class);
        kryo.register(PlayerSelfPenisMouth.class);
        kryo.register(PlayerSelfPenisNipple.class);
        kryo.register(PlayerSelfPenisVagina.class);
        kryo.register(PlayerSelfTailAnus.class);
        kryo.register(PlayerSelfTailMouth.class);
        kryo.register(PlayerSelfTailNipple.class);
        kryo.register(PlayerSelfTailVagina.class);
        kryo.register(PlayerSelfTongueAnus.class);
        kryo.register(PlayerSelfTongueMouth.class);
        kryo.register(PlayerSelfTongueNipple.class);
        kryo.register(PlayerSelfTongueVagina.class);

        kryo.register(BackToWall.class);
        kryo.register(ChairSex.class);
        kryo.register(Cowgirl.class);
        kryo.register(DoggyStyle.class);
        kryo.register(FaceSitting.class);
        kryo.register(FaceToWall.class);
        kryo.register(GloryHole.class);
        kryo.register(HandHolding.class);
        kryo.register(KneelingOral.class);
        kryo.register(Masturbation.class);
        kryo.register(MatingPress.class);
        kryo.register(MilkingStall.class);
        kryo.register(Missionary.class);
        kryo.register(MissionaryDesk.class);
        kryo.register(SixtyNine.class);
        kryo.register(Standing.class);
        kryo.register(StocksSex.class);
    }

}
